services:
  credit-analysis-app:
    image: credit-analysis-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_RABBITMQ_HOST=rabbit-mq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest